### PR TITLE
Clean up PR

### PR DESCRIPTION
**Pull request by pvoznenko**
Hi @sebarmeli,

What was done:
- updated readme - added missing documentation; 
- updated console application - added missing methods;
- updated tests -  added missing tests; 
- fixed new methods - few of them was never working (undefined errors);
- fixed jsdoc - methods with callbacks had wrong jsdoc with misleading information, my IDEA went crazy :)
- cleaned and refactored code;
- fixed some typos.

If you would like I can comment row by row what and why was changed.

Unfortunately now I can not comment row by row, need to be social with my family :)

Have a nice week!
Best Regards,
Pavlo Voznenko

### CODE REVIEW

**Comment by pvoznenko** [comment]
Sorry that everything is in one commit :(

**Comment by sebarmeli** [comment]
@pvoznenko I saw your message on Twitter, do you want me to hold on before merging?

**Comment by pvoznenko** [comment]
Hi @sebarmeli , thank you for asking.

I reviewed it again, looks good for me. 

If you think it is good enough, you can merge it.

Have a nice week!
Cheers,
Pavlo

**Comment by sebarmeli** [comment]
After you resolve the conflict, I'll merge it in

**Comment by pvoznenko** [comment]
Hi @sebarmeli , conflict resolved :)

**Comment by sebarmeli** [comment]
Published 0.0.7

**Comment by pvoznenko** [comment]
Hi @sebarmeli , could you please publish it to npm also? https://www.npmjs.com/package/bamboo-api thanks

**Comment by sebarmeli** [comment]
already published - version 0.0.7

**Comment by pvoznenko** [comment]
NPM still says that it is 0.0.5. I saw that package.json is updated, maybe something changed in a way how npm version update works? https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by sebarmeli** [comment]
Not sure why the UI is not updated - have you tried running ```rm -rf node_modules && npm i``` on a package requiring it

**Comment by pvoznenko** [comment]
sorry, my fault, yes you right, checked through console:

```bash
% npm info bamboo-api                                                                                                                                                     !8033

{ name: 'bamboo-api',
  description: 'Node wrapper around Atlassian Bamboo API',
  'dist-tags': { latest: '0.0.7' },
  versions: [ '0.0.1', '0.0.2', '0.0.3', '0.0.5', '0.0.7' ],
  maintainers: [ 'sebarmeli <seba.armeli@gmail.com>' ],
  time:
   { modified: '2016-05-10T14:17:26.370Z',
     created: '2012-11-08T03:25:08.546Z',
     '0.0.1': '2012-11-08T03:25:11.843Z',
     '0.0.2': '2013-03-11T11:07:25.161Z',
     '0.0.3': '2014-07-27T21:08:22.964Z',
     '0.0.5': '2014-09-19T17:53:05.562Z',
     '0.0.7': '2016-05-10T14:17:26.370Z' },
  author: 'Sebastiano Armeli-Battana <seba.armeli@gmail.com>',
  repository:
   { type: 'git',
     url: 'git+https://github.com/sebarmeli/bamboo-api.git' },
  keywords: [ 'bamboo', 'rest-api', 'ci' ],
  license:
   [ { type: 'MIT',
       url: 'http://github.com/sebarmeli/bamboo-api/raw/master/LICENSE' } ],
  readmeFilename: 'README.md',
  homepage: 'https://github.com/sebarmeli/bamboo-api#readme',
  bugs: { url: 'https://github.com/sebarmeli/bamboo-api/issues' },
  contributors: [ 'Pavlo Voznenko <p.voznenko@gmail.com> (https://twitter.com/pvoznenko/)' ],
  version: '0.0.7',
  main: './lib/bamboo.js',
  scripts: { test: 'mocha' },
  bin: { 'bamboo-api': './bin/bamboo-api' },
  dependencies: { request: '~2.11.4', underscore: '~1.4.2', commander: '~1.0.5' },
  devDependencies: { mocha: '1.20.1', should: '~1.2.1', nock: '8.0.0' },
  directories: { bin: './bin', lib: './lib', test: './test' },
  engine: { node: '~0.6.x' },
  gitHead: '69003685db86867c6186b77a1f357e19b3e1c06b',
  dist:
   { shasum: '275e7997538b6a3ee3443d3ccb927bbbb362296b',
     tarball: 'https://registry.npmjs.org/bamboo-api/-/bamboo-api-0.0.7.tgz' } }

```

**Comment by pvoznenko** [comment]
all good. Sorry for bothering :)

**Pull request merged**
